name: Deploy to Raspberry Pi

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  TOKEN: ${{ secrets.TOKEN }}

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    runs-on: self-hosted

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'npm'
          
      - name: Install Dependencies
        run: npm install
        
      - name: Install PM2 just in case
        run: npm install pm2 -g

      - name: Install tsc
        run: npm install tsc -g

      - name: Kill PM2 instance
        run: npm run pm2:kill

      - name: Start PM2 instance
        if: always()
        run: npm run pm2
